export const COUNTRIES = {
  Afganistan: "AF",
  "Wyspy Alandzkie": "AX",
  Albania: "AL",
  Algieria: "DZ",
  "Samoa Amerykańskie": "AS",
  Andorra: "AD",
  Angola: "AO",
  Anguilla: "AI",
  Antarktyda: "AQ",
  "Antigua i Barbuda": "AG",
  Argentyna: "AR",
  Armenia: "AM",
  Aruba: "AW",
  Australia: "AU",
  Austria: "AT",
  Azerbejdżan: "AZ",
  Bahamas: "BS",
  Bahrain: "BH",
  Bangladesz: "BD",
  Barbados: "BB",
  Belarus: "BY",
  Belgia: "BE",
  Belize: "BZ",
  Benin: "BJ",
  Bermuda: "BM",
  Bhutan: "BT",
  Bolivia: "BO",
  "Bośnia i Hercegowina": "BA",
  Botswana: "BW",
  "Wyspa Bouveta": "BV",
  Brazylia: "BR",
  "Brytyjskie Terytorium Oceanu Indyjskiego": "IO",
  Brunei: "BN",
  Bułgaria: "BG",
  "Burkina Faso": "BF",
  Burundi: "BI",
  Kambodża: "KH",
  Kamerun: "CM",
  Kanada: "CA",
  "Republika Zielonego Przylądka": "CV",
  Kajmana: "KY",
  "Republika Środkowoafrykańska": "CF",
  Dzad: "TD",
  Chile: "CL",
  Chiny: "CN",
  "Wyspa Bożego Narodzenia": "CX",
  "Wyspy Kokosowe": "CC",
  Kolumbia: "CO",
  Komory: "KM",
  Kongo: "CG",
  "Wyspy Cooka": "CK",
  Kostaryka: "CR",
  "Wybrzeże Kości Słoniowej": "CI",
  Chorwacja: "HR",
  Kuba: "CU",
  Cypr: "CY",
  Czechy: "CZ",
  "Demokratyczna Republika Konga": "CD",
  Dania: "DK",
  Dżibuti: "DJ",
  Dominika: "DM",
  Dominikana: "DO",
  Ekwador: "EC",
  Egypt: "EG",
  Egipt: "EG",
  Salwador: "SV",
  "Gwinea Równikowa": "GQ",
  Erytrea: "ER",
  Estonia: "EE",
  Etiopia: "ET",
  Falklandy: "FK",
  "Wyspy Owcze": "FO",
  Fidżi: "FJ",
  Finlandia: "FI",
  Francja: "FR",
  "Gujana Francuska": "GF",
  "Polynezja Francuska": "PF",
  "Francuskie Terytoria Południowe i Antarktyczne": "TF",
  Gabon: "GA",
  Gambia: "GM",
  Gruzja: "GE",
  Niemcy: "DE",
  Ghana: "GH",
  Gibraltar: "GI",
  Grecja: "GR",
  Greenlandia: "GL",
  Grenada: "GD",
  Gwadelupa: "GP",
  Guam: "GU",
  Gwatemala: "GT",
  Gwinea: "GN",
  "Gwinea-Bissau": "GW",
  Gujana: "GY",
  Haiti: "HT",
  "Wyspy Heard i McDonalda": "HM",
  Honduras: "HN",
  "Hong Kong": "HK",
  Węgry: "HU",
  Islandia: "IS",
  India: "IN",
  Indonezja: "ID",
  Iran: "IR",
  Irak: "IQ",
  Irlandia: "IE",
  "Wyspa Mann": "IM",
  Izrael: "IL",
  Włochy: "IT",
  Jamajka: "JM",
  Japonia: "JP",
  Jersey: "JE",
  Jordania: "JO",
  Kazachstan: "KZ",
  Kenia: "KE",
  Kiribati: "KI",
  Kuwejt: "KW",
  Kirgistan: "KG",
  Laos: "LA",
  Łotwa: "LV",
  Liban: "LB",
  Lesotho: "LS",
  Liberia: "LR",
  Libia: "LY",
  Liechtenstein: "LI",
  Litwa: "LT",
  Luxemburg: "LU",
  Makau: "MO",
  Macedonia: "MK",
  Madagaskar: "MG",
  Malawi: "MW",
  Malezja: "MY",
  Malediwy: "MV",
  Mali: "ML",
  Malta: "MT",
  "Wyspy Marshalla": "MH",
  Martynika: "MQ",
  Mauretania: "MR",
  Mauritius: "MU",
  Majotta: "YT",
  Meksyk: "MX",
  Mikronezja: "FM",
  Mołdawia: "MD",
  Monako: "MC",
  Mongolia: "MN",
  Czarnogóra: "ME",
  Montserrat: "MS",
  Maroko: "MA",
  Mozambik: "MZ",
  Birma: "MM",
  Namibia: "NA",
  Nauru: "NR",
  Nepal: "NP",
  "Antyle Holenderskie": "AN",
  Holandia: "NL",
  "Nowa Kaledonia": "NC",
  "Nowa Zelandia": "NZ",
  Nikaragua: "NI",
  Niger: "NE",
  Nigeria: "NG",
  Niue: "NU",
  Norfolk: "NF",
  "Korea Północna": "KP",
  "Mariany Północne": "MP",
  Norwegia: "NO",
  Oman: "OM",
  Pakistan: "PK",
  Palau: "PW",
  Palestyna: "PS",
  Panama: "PA",
  "Papua Nowa Gwinea": "PG",
  Paragwaj: "PY",
  Peru: "PE",
  Filipiny: "PH",
  Pitcairn: "PN",
  Polska: "PL",
  Portugalia: "PT",
  Portoryko: "PR",
  Katar: "QA",
  Reunion: "RE",
  Rumunia: "RO",
  Rosja: "RU",
  Rwanda: "RW",
  "Saint Barthelemy": "BL",
  "Wyspa Św. Heleny": "SH",
  "Saint Kitts i Nevis": "KN",
  "Saint Lucia": "LC",
  "Saint Martin": "MF",
  "Saint Pierre i Miquelon": "PM",
  "Saint Vincent i Grenadyny": "VC",
  Samoa: "WS",
  "San Marino": "SM",
  "Wyspy Świętego Tomasza i Książęca": "ST",
  "Arabia Saudyjska": "SA",
  Senegal: "SN",
  Serbia: "RS",
  Seszele: "SC",
  "Sierra Leone": "SL",
  Singapur: "SG",
  Słowacja: "SK",
  Słowenia: "SI",
  "Wyspy Solomona": "SB",
  Somalia: "SO",
  "Republika Południowej Afryki": "ZA",
  "Georgia Południowa i Sandwich Południowy": "GS",
  "Korea Południowa": "KR",
  Hiszpania: "ES",
  "Sri Lanka": "LK",
  Sudan: "SD",
  Surinam: "SR",
  "Svalbard i Jan Mayen": "SJ",
  Swaziland: "SZ",
  Szwecja: "SE",
  Szwajcaria: "CH",
  Syria: "SY",
  Taiwan: "TW",
  Tadżykistan: "TJ",
  Tanzania: "TZ",
  Tajlandia: "TH",
  "Timor Wschodni": "TL",
  Togo: "TG",
  Tokelau: "TK",
  Tonga: "TO",
  "Trinidad i Tobago": "TT",
  Tunezja: "TN",
  Turcja: "TR",
  Turkmenistan: "TM",
  "Turks i Caicos": "TC",
  Tuvalu: "TV",
  Uganda: "UG",
  Ukraina: "UA",
  "Zjednoczone Emiraty Arabskie": "AE",
  "Wielka Brytania": "GB",
  "Dalekie Wyspy Mniejsze Stanów Zjednoczonych": "UM",
  "USA": "US",
  Urugwaj: "UY",
  Uzbekistan: "UZ",
  Vanuatu: "VU",
  Watykan: "VA",
  Wenezuela: "VE",
  Wietnam: "VN",
  "Brytyjskie Wyspy Dziewicze": "VG",
  "Wyspy Dziewicze Stanów Zjednoczonych": "VI",
  "Wallis i Futuna": "WF",
  "Sahara Zachodnia": "EH",
  Jemen: "YE",
  Zambia: "ZM",
  Zimbabwe: "ZW",
  Anglia: "EN",
  Szkocja: "SC",
  Walia: "WL",
  "Irlandia Północna": "IP",
  Curacao: "CW"
} as const;

export type CountryName = keyof typeof COUNTRIES;
export type CountryCode = (typeof COUNTRIES)[CountryName];
