export const TEAM_ALIASES = {
  "Arabia Saudyjska": "KSA",
  Afganistan: 'AFG',
  "Wyspy Alandzkie": 'ALA',
  Albania: 'ALB',
  Algieria: 'ALG',
  "Samoa Amerykańskie": 'ASA',
  Andorra: 'AND',
  Angola: 'ANG',
  Anguilla: 'AIA',
  Antarktyda: 'ATA',
  "Antigua i Barbuda": 'ATG',
  Argentyna: 'ARG',
  Armenia: 'ARM',
  Aruba: 'ARU',
  Australia: 'AUS',
  Austria: 'AUT',
  Azerbejdżan: 'AZE',
  Bahamas: 'BAH',
  Bahrain: 'BHR',
  Bangladesz: 'BAN',
  Barbados: 'BRB',
  Belarus: 'BLR',
  Belgia: 'BEL',
  Belize: 'BLZ',
  Benin: 'BEN',
  Bermuda: 'BER',
  Bhutan: 'BHU',
  Bolivia: 'BOL',
  "Bośnia i Hercegowina": 'BIH',
  Botswana: 'BOT',
  "Wyspa Bouveta": 'BVT',
  Brazylia: 'BRA',
  Brunei: 'BRU',
  Bułgaria: 'BUL',
  "Burkina Faso": 'BFA',
  Burundi: 'BDI',
  Kambodża: 'CAM',
  Kamerun: 'CMR',
  Kanada: 'CAN',
  "Republika Zielonego Przylądka": 'CPV',
  Kajmana: 'CAY',
  "Republika Środkowoafrykańska": 'CTA',
  Dzad: 'CHA',
  Chile: 'CHI',
  Chiny: 'CHN',
  Kolumbia: 'COL',
  Komory: 'COM',
  Kongo: 'CGO',
  "Demokratyczna Republika Konga": 'COD',
  Kostaryka: 'CRC',
  Chorwacja: 'CRO',
  Kuba: 'CUB',
  Cypr: 'CYP',
  Czechy: 'CZE',
  Dania: 'DEN',
  Dżibuti: 'DJI',
  Dominika: 'DMA',
  Dominikana: 'DOM',
  Ekwador: 'ECU',
  Egypt: 'EGY',
  Egipt: 'EGY',
  Salwador: 'ESA',
  "Gwinea Równikowa": 'EQG',
  Erytrea: 'ERI',
  Estonia: 'EST',
  Etiopia: 'ETH',
  Fidżi: 'FIJ',
  Finlandia: 'FIN',
  Francja: 'FRA',
  Gabon: 'GAB',
  Gambia: 'GAM',
  Gruzja: 'GEO',
  Niemcy: 'GER',
  Ghana: 'GHA',
  Grecja: 'GRE',
  Grenada: 'GRN',
  Gwatemala: 'GUA',
  Gwinea: 'GUI',
  "Gwinea-Bissau": 'GNB',
  Gujana: 'GUY',
  Haiti: 'HAI',
  Honduras: 'HON',
  "Hong Kong": 'HKG',
  Węgry: 'HUN',
  Islandia: 'ISL',
  India: 'IND',
  Indonezja: 'IDN',
  Iran: 'IRN',
  Irak: 'IRQ',
  Irlandia: 'IRL',
  Izrael: 'ISR',
  Włochy: 'ITA',
  Jamajka: 'JAM',
  Japonia: 'JPN',
  Jordania: 'JOR',
  Kazachstan: 'KAZ',
  Kenia: 'KEN',
  Kiribati: 'KIR',
  Kuwejt: 'KUW',
  Kirgistan: 'KGZ',
  Laos: 'LAO',
  Łotwa: 'LVA',
  Liban: 'LIB',
  Lesotho: 'LES',
  Liberia: 'LBR',
  Libia: 'LBA',
  Liechtenstein: 'LIE',
  Litwa: 'LTU',
  Luxemburg: 'LUX',
  Makau: 'MAC',
  Macedonia: 'MKD',
  Madagaskar: 'MAD',
  Malawi: 'MWI',
  Malezja: 'MAS',
  Malediwy: 'MDV',
  Mali: 'MLI',
  Malta: 'MLT',
  "Wyspy Marshalla": 'MHL',
  Mauretania: 'MTN',
  Mauritius: 'MRI',
  Meksyk: 'MEX',
  Mikronezja: 'FSM',
  Mołdawia: 'MDA',
  Monako: 'MON',
  Mongolia: 'MGL',
  Czarnogóra: 'MNE',
  Maroko: 'MAR',
  Mozambik: 'MOZ',
  Namibia: 'NAM',
  Nauru: 'NRU',
  Nepal: 'NEP',
  Holandia: 'NED',
  "Nowa Zelandia": 'NZL',
  Nikaragua: 'NCA',
  Niger: 'NIG',
  Nigeria: 'NGA',
  "Korea Północna": 'PRK',
  "Korea Południowa": 'KOR',
  Norwegia: 'NOR',
  Oman: 'OMA',
  Pakistan: 'PAK',
  Panama: 'PAN',
  "Papua Nowa Gwinea": 'PNG',
  Paragwaj: 'PAR',
  Peru: 'PER',
  Filipiny: 'PHI',
  Polska: 'POL',
  Portugalia: 'POR',
  Katar: 'QAT',
  Rumunia: 'ROU',
  Rosja: 'RUS',
  Rwanda: 'RWA',
  Samoa: 'SAM',
  "San Marino": 'SMR',
  Senegal: 'SEN',
  Serbia: 'SRB',
  Seszele: 'SEY',
  "Sierra Leone": 'SLE',
  Singapur: 'SIN',
  Słowacja: 'SVK',
  Słowenia: 'SVN',
  Somalia: 'SOM',
  "Republika Południowej Afryki": 'RSA',
  Hiszpania: 'ESP',
  "Sri Lanka": 'SRI',
  Sudan: 'SDN',
  Surinam: 'SUR',
  Szwecja: 'SWE',
  Szwajcaria: 'SUI',
  Syria: 'SYR',
  Taiwan: 'TPE',
  Tadżykistan: 'TJK',
  Tanzania: 'TAN',
  Tajlandia: 'THA',
  Togo: 'TOG',
  Tonga: 'TGA',
  "Trinidad i Tobago": 'TRI',
  Tunezja: 'TUN',
  Turcja: 'TUR',
  Turkmenistan: 'TKM',
  Uganda: 'UGA',
  Ukraina: 'UKR',
  "Zjednoczone Emiraty Arabskie": 'UAE',
  "Wielka Brytania": 'GBR',
  USA: 'USA',
  Urugwaj: 'URU',
  Uzbekistan: 'UZB',
  Vanuatu: 'VAN',
  Watykan: 'VAT',
  Wenezuela: 'VEN',
  Wietnam: 'VIE',
  "Wybrzeże Kości Słoniowej": 'CIV',
  Zambia: 'ZAM',
  Zimbabwe: 'ZIM',

  // special UK teams (football reality)
  Anglia: 'ENG',
  Szkocja: 'SCO',
  Walia: 'WAL',
  "Irlandia Północna": 'NIR',
  Curacao: 'CUW'
} as const;

export type TeamName = keyof typeof TEAM_ALIASES;
